### PR TITLE
Add search input

### PR DESCRIPTION
**Pull request by poacher2k**
Add search input for searching through filenames. Also adds option to get images based on orientation (eg. `orientation:landscape`) and extension (eg. `extension:png`)

### CODE REVIEW

**Comment by a-apiko** [comment]
Wow, this is exactly the feature I wanted to get! When it will be merged?

**Comment by robinpyon** [comment]
Thanks @poacher2k, this is great! Apols for the glacial response, will be looking into this next.

**Comment by poacher2k** [comment]
@robinpyon : nw, thank you for the nice plugin! I'm not very experienced with TypeScript, nor did I dive very deeply into the architecture here, so I'm sure I messed up a bit.

**Comment by robinpyon** [comment]
@poacher2k Not at all!

That's now in `0.4.0` – do have a go and let me know if you come across any issues. I took the opportunity to try and do a bit of (much-needed) cleaning too.

I've also made a few minor tweaks to the search – those requests are debounced, there's a reset search button and those shortcut options you've added (e.g. orientation:landscape) are also additive, so in theory it's possible to do a search like `orientation:landscape extension:jpg another_search_term_here`

**Comment by poacher2k** [comment]
Awesome man! Looking good 💯 Thank you for merging and improving :)

**Pull request merged**
